FROM node:20-alpine

# Install native chromium and dependencies for rendering PDF
RUN apk add --no-cache chromium

WORKDIR /workspace

COPY package.json package-lock.json ./
RUN npm install -g npm@11.6.1 && npm ci

COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev"]
